name: Sync from Obsidian Vault

on:
  # Trigger when changes are pushed to obsidian-vault branch
  repository_dispatch:
    types: [obsidian-update]
  # Manual trigger
  workflow_dispatch:
  # Schedule: Check for updates every 6 hours
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Jekyll repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Checkout Obsidian vault
      uses: actions/checkout@v4
      with:
        repository: jonathan-nguyen/obsidian-vault
        token: ${{ secrets.OBSIDIAN_VAULT_TOKEN }}
        path: obsidian-vault
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        pip install pyyaml
        
    - name: Run Obsidian sync
      run: |
        python scripts/obsidian-sync.py \
          --obsidian-path obsidian-vault \
          --jekyll-path .
          
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _notes/
        git commit -m "📝 Sync from Obsidian vault" || exit 0
        
    - name: Push changes
      if: steps.changes.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main